# Site settings
title: Command Line Tips
email: ben@benmccormick.org
description: > # this means to ignore newlines until "baseurl:"
    Command Line Tips from Ben McCormick.  Short practical 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benmccormick.org" # the base hostname & protocol for your site
twitter_username: ben336
github_username:  benmccormick

# Build settings
markdown: kramdown

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
