# Site settings
title: Command Line Tips
subtitle: Quick Snippets of CLI goodness
email: ben@benmccormick.org
description: > # this means to ignore newlines until "baseurl:"
    Command Line Tips from Ben McCormick.  Short practical snippets from day to day practice.
baseurl: "/cli_blog" # the subpath of your site, e.g. /blog/
url: "http://benmccormick.github.io" # the base hostname & protocol for your site
twitter_username: ben336
github_username:  benmccormick

# Build settings
markdown: kramdown

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

search: google

sharing:
  - twitter
  - email

# Defaults to sharing with links (for speed and privacy)
# To use javascript share buttons, set share_with: buttons
share_with: links

# Embed comments, options: false, facebook, disqus
comments: false

# Center the text in post and page headings.
center_headings: true
